# Generated by Django 5.1.2 on 2024-11-18 01:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_http_app', '0002_alter_bid_options_alter_bid_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLatency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(blank=True, max_length=255, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(auto_now_add=True)),
                ('latency', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
