# Generated by Django 5.1.2 on 2024-12-09 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_http_app', '0003_requestlatency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlatency',
            name='latency',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True),
        ),
    ]
