# Generated by Django 5.1.2 on 2024-12-10 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_http_app', '0005_alter_requestlatency_latency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='owner',
        ),
    ]
