# Generated by Django 5.1.2 on 2025-01-07 03:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_http_app', '0006_remove_property_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertySpecifications',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('street_name', models.CharField(blank=True, max_length=255, null=True)),
                ('property_type', models.CharField(blank=True, max_length=255, null=True)),
                ('transacted_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('area_sqft', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit_price_psf', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
                ('type_of_area', models.CharField(blank=True, max_length=255, null=True)),
                ('area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit_price_psm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tenure', models.CharField(blank=True, max_length=255, null=True)),
                ('postal_district', models.CharField(blank=True, max_length=255, null=True)),
                ('floor_level', models.CharField(blank=True, max_length=255, null=True)),
                ('prediction', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_specifications', to='property_http_app.property')),
            ],
        ),
    ]
