name: Node.js CI for GitHub Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    
    # Set up Node.js
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    # Install dependencies
    - run: npm ci

    # Install Angular CLI
    - run: npm install -g @angular/cli

    # Change directory to Angular project folder
    - run: cd Angular_WebSocket_Frontend/

    # Build the Angular project with SSL disabled
    - run: ng build --prod --base-href /Angular_WebSocket_Frontend/ --ssl=false
